- category: --Deadly Life--
  songs: 
    - name: "BOX 15.mp3"
      length: 244
    - name: "BOX 16.mp3"
      length: 331
    - name: "Ikoroshia.mp3"
      length: 282
    - name: "Ekoroshia.mp3"
      length: 424
    - name: "Despair Searching.mp3"
      length: 263
    - name: "Hope Searching.mp3"
      length: 501