- area: Basement
  background: gs4
  bglock: true
  evidence_mod: FFA
  locking_allowed: false
  iniswap_allowed: true
  reachable_areas: Courtroom 1
- area: Courtroom 1
  background: gs5
  bglock: false
  evidence_mod: CM
  locking_allowed: true
  iniswap_allowed: true
  reachable_areas: Courtroom,\ 2, Basement
  gm_iclock_allowed: false
  afk_delay: 5
- area: Courtroom, 2
  background: gs4
  bglock: false
  evidence_mod: Mods
  locking_allowed: false
  iniswap_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  afk_delay: 10
  afk_sendto: 3