# A sample background list document
# List your background folder names, one per line.
# Start each line with -
- gs4
- Class Trial Debate Room V3-1_HD
- DEOMDE B-612-152-W2V
- klastrial dibeit rum
- Nave Exterior
- MECHAS BG
- Sala de Comandos
- DR2 Dining_HD
- 999 1st Class Living Room_HD
- Espacio
- Chisaus Rojo
- Puerto lol
- DR2 Park_HD
- Lomas
- V3 School Store_HD
- Planeta X
- Infierno
- Dolor Eterno
- Agonia
- V3 Underground Passage_HD
- Subterraneo