# A sample character list document
# List your character folder names, one per line.
# Start each line with -
- FANO
- Amber
- CABBASHO
- LabyRS_HD
- Ryuk_HD
- Syakesan_HD
- Super_Zazenllamer_Syakesan_ESENCIA_HD
- Concha
- Meiggs
- ElHermano
- VENOM NANAYA
- MAVM
- Zazenllamer (Goku) Ladron de cuerpos
- Jesse Pinkman
- walter
- Emiliano Arancio
- Saul Goodman
- Persona1
- Persona2
- Persona3
- Persona4
- Persona5
- Persona6
- Persona7
- Persona8
- Persona9
- Persona10
- Persona11
- Persona12
- Persona13
- Persona14
- Persona15