# A sample character list document
# List your character folder names, one per line.
# Start each line with -
- Fuego Fresquito
- Emiliano Arancio
- Marco
- Goku
- Persona1
- Persona2
- Persona3
- Persona4
- Persona5
- Persona6
- Persona7
- Persona8
- Persona9
- Persona10